pngout: false
advpng:
  level: 2
jhead: true
jpegtran: true
jpegrecompress: 
  allow_lossy: true
  quality: 2
svgo: false
oxipng:
  level: 3
optipng:
  level: 5
pngquant: false
jpegoptim:
  allow_lossy: true
  max_quality: 85