Metrics/ModuleLength:
  Exclude:
  - 'spec/**/*_spec.rb' # minitest

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*_spec.rb' # RSpec

Metrics/AbcSize:
  Exclude:
  - 'spec/**/*_spec.rb' # RSpec

Naming/VariableNumber:
  Exclude:
  - 'spec/**/*_spec.rb' # RSpec
