Metrics/ModuleLength:
  Exclude:
  - 'test/**/*_test.rb' # minitest

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*_spec.rb' # RSpec

Metrics/AbcSize:
  Exclude:
  - 'spec/**/*_spec.rb' # RSpec

Style/Documentation:
  Exclude:
  - 'test/**/*_test.rb' # minitest

Naming/VariableNumber:
  Exclude:
  - 'spec/**/*_spec.rb' # RSpec
