# Defaults: https://github.com/bbatsov/rubocop/blob/master/config/default.yml
require: rubocop-rails

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

# Accept both [:a, :b, :c] and %i[a b c]
Style/SymbolArray:
  Enabled: false

Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 80

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

# Accept Japanese characters in comments
Style/AsciiComments:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

# Allow %r as a regular expression syntax
Style/RegexpLiteral:
  Enabled: false

# Sometimes you absolutely want to be sure you have a boolean.
# The guide for this cop even admits that their recommendation
# doesn't logically equal !!.
Style/DoubleNegation:
  Enabled: false

# Developers agreed that it's harder to read assignments across multiple lines.
Style/ConditionalAssignment:
  Enabled: false

# Disallow %w[]
Style/WordArray:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

# It sometimes make sense to use #length == 0 or #size == 0, for example, when the object does not implement Enumerable.
Style/ZeroLengthPredicate:
  Enabled: false

# > 0, == 0, < 0 is more common in major programming languages.
# In addition, sometimes it is necessary to compare a non-numeric value with 0 (e.g. params[:size] == 0 but it can be nil)
Style/NumericPredicate:
  Enabled: false

Metrics/ParameterLists:
  Max: 6

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
  - 'spec/**/*_spec.rb' # minitest

Metrics/ClassLength:
  Enabled: false

Naming/VariableNumber:
  Exclude:
  - 'spec/**/*_spec.rb' # RSpec

AllCops:
  NewCops: enable
  Exclude:
    - vendor/bundle/**/*
    - vendor/**/*.rb 
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - bin/*

Lint/EmptyBlock:
  Exclude:
    - 'spec/**/*_spec.rb' # RSpec

Rails/Output:
  Enabled: true

Rails/DynamicFindBy:
  Enabled: false

Metrics/BlockLength:
  Max: 80
  Exclude:
    # ActiveAdmin's DSL prefers long blocks
    - app/admin/**/*
    - config/**/*
    - 'spec/**/*_spec.rb' # RSpec

Rails/UniqueValidationWithoutIndex:
  Exclude:
    - app/models/user_gender_interest.rb

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/InverseOf:
  Enabled: false